### ISSUE TITLE
前端示例代码可以贴出来吗？

### ISSUE THREAD

**Issue by ffanywudi** [myliuxia/slide-verify-after#1]
betterboy@vip.qq.com可以发给我前端代码吗？

**Comment by myliuxia** [comment]
前端示例在另一个仓库（slide-verify-front）

**Comment by ffanywudi** [comment]
大神你好，我们项目都是juery。感觉要被人笑话了。。。。。。
可以给一个非vue的前端示例吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myliuxia/slide-verify-after"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 中午11:18
收件人:&nbsp;"myliuxia/slide-verify-after"<slide-verify-after@noreply.github.com&gt;;
抄送:&nbsp;"-饭饭、↘"<380463039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [myliuxia/slide-verify-after] 前端示例代码可以贴出来吗？ (#1)





 
Closed #1.
